version: '3'

services:

  javaSDK:
    build:
      context: .
    image: javasdk
    container_name: javaSDK
    environment:
      - PLIVO_AUTH_ID=${PLIVO_AUTH_ID}
      - PLIVO_AUTH_TOKEN=${PLIVO_AUTH_TOKEN}
      - PLIVO_API_DEV_HOST=${PLIVO_API_DEV_HOST}
      - PLIVO_API_PROD_HOST=${PLIVO_API_PROD_HOST}
    volumes:
      - .:/usr/src/app
    stdin_open: true 
    tty: true