---
parent: central
serviceName: plivo-java
language: java-sdk

secrets:
  files:
    SONATYPE_SECRET_RING_FILE: "secring.gpg"

build:
  command: |
      chmod 755 secring.gpg
      export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      ./gradlew createPom
      ./build.sh
      ./gradlew fatJar

postDeployJobs:
  prod:
    - name: plivo/messaging-qa/javaSDKSmoke
      disabled: false
